# Model Specification

model: DeepSnake
model_args:
  backbone: Xception
  model_dim: 1024
  iterations: 4
  coord_features: true
  stop_grad: true
  weight_sharing: true
  head: SnakeHead
loss_function: stepwise(SoftDTW(0.001))

# Data args
batch_size: 16
# dataset:  CALFIN
# data_root: '../CALFIN/training/data'
# data_channels: [2]
dataset: TUD-MS
data_root: '../aicore/uc1_new/'
tile_size: 256
vertices: 64
